services:
  app:
    build: .
    container_name: task_oriented_dataset_search
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://tods_mongodb:27017/paperdatabase"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"
    command: python

  mongo:
    image: mongo:6.0
    container_name: tods_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
